steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'e-commerce', '--image', 'gcr.io/cloudrun/zokso:latest', '--platform', 'managed', '--region', 'asia-east1', '--allow-unauthenticated']
  env:
    - 'NODE_ENV=production'
